### ISSUE TITLE
Fails to compile in ghc 8.0.1

### ISSUE THREAD

**Issue by Saulzar** [pa-ba/compdata#20]
I'm seeing a bunch of errors like this:

src/Data/Comp/Render.hs:32:22: error:
    • Couldn't match type ‘Tree NodeInfo -> IO ()’ with ‘IO ()’
      Expected type: Term f -> IO ()
        Actual type: Term f -> Tree NodeInfo -> IO ()
    • Probable cause: ‘(.)’ is applied to too few arguments
      In the expression:
        writeHtmlTree file . fmap (\ n -> NodeInfo n "") . stringTree
      In an equation for ‘writeHtmlTerm’:
          writeHtmlTerm file
            = writeHtmlTree file . fmap (\ n -> NodeInfo n "") . stringTree

src/Data/Comp/Render.hs:32:36: error:
    • Couldn't match type ‘[Char]’ with ‘Maybe FilePath’
      Expected type: Maybe FilePath
        Actual type: FilePath
    • In the first argument of ‘writeHtmlTree’, namely ‘file’
      In the first argument of ‘(.)’, namely ‘writeHtmlTree file’
      In the expression:
        writeHtmlTree file . fmap (\ n -> NodeInfo n "") . stringTree

**Comment by eeasley-coursera** [comment]
Pretty sure this is fixed by #19.
